const CART_ACTIONS = {
  OPEN_CART: 'OPEN_CART',
  CLOSE_CART: 'CLOSE_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_QUANTITY:' UPDATE_QUANTITY',
  REMOVE_ITEM:'REMOVE_ITEM',
  SET_ITEMS: 'SET_ITEMS'
};
export default CART_ACTIONS;
